### ISSUE TITLE
Generating peer info for a multiaddr using p2p-circuit

### ISSUE THREAD

**Issue by bennewhall** [vyzo/gerbil-libp2p#16]
# Description of Issue
I want to connect to peer A through a circuit relay. To do so, I obtain this address
``` /ip4/<someip>/tcp/<someport>/ipfs/<relay-peerID>/p2p-circuit/ipfs/<A-peerID>```

When I go to convert this string to a peer-info, I run

``` (string->peer-info "/ip4/<someip>/tcp/<someport>/ipfs/<relay-peerID>/p2p-circuit/ipfs/<A-peerID>") ```

This results in the error 

``` *** ERROR IN ##start-main -- Malformed peer info ```

# Possible Cause

The parsing from string to peer-info only seems to assume there is <= 1 "/ipfs/" occurrence in the string.

https://github.com/vyzo/gerbil-libp2p/blob/01c08f18a8bd736ee1f226cbb2d5ffc7c3525a3c/libp2p/peer.ss#L38-L49

**Comment by vyzo** [comment]
yeah, care for a patch? We should slao rename ipfs to p2p in multiaddr.

**Comment by bennewhall** [comment]
Yeah! I'm planning on submitting a pr sometime later today. I could also do a separate one for p2p
